title: Aryan Shrimali's site
description: "Class of 2026"
owner_name: Aryan Shrimali
github_username: Aryanshrimali08
github_repo: "student"
baseurl: "/student"
future: true

# Cayman theme
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Pages to appear in the navigation
header_pages:
  - index.md          # Home page
  - about.md          # About page
  - blog.md           # Blog page (optional)
  - logintoolkit.md   # Other page
  - search.md         # Optional search page
